In [1]:
%load_ext nb_black

<IPython.core.display.Javascript object>

In [2]:
import numpy as np
import pandas as pd
from sklearn import metrics as m

<IPython.core.display.Javascript object>

In [3]:
pd_acc_class0 = pd.read_csv("pd_acc_class0.txt")
pd_ypredproba_all_class0 = pd.read_csv("pd_ypredproba_all_class0.txt")
pd_ypredconfprob_all_class0 = pd.read_csv("pd_ypredconfprob_all_class0.txt")

<IPython.core.display.Javascript object>

In [4]:
pd_acc_class1 = pd.read_csv("pd_acc_class1.txt")
pd_ypredproba_all_class1 = pd.read_csv("pd_ypredproba_all_class1.txt")
pd_ypredconfprob_all_class1 = pd.read_csv("pd_ypredconfprob_all_class1.txt")

<IPython.core.display.Javascript object>

In [5]:
pd_acc_class2 = pd.read_csv("pd_acc_class2.txt")
pd_ypredproba_all_class2 = pd.read_csv("pd_ypredproba_all_class2.txt")
pd_ypredconfprob_all_class2 = pd.read_csv("pd_ypredconfprob_all_class2.txt")

<IPython.core.display.Javascript object>

In [6]:
ytest_class0 = pd.read_csv("ytest_class0.txt")
ytest_class1 = pd.read_csv("ytest_class1.txt")
ytest_class2 = pd.read_csv("ytest_class2.txt")
ytest_original = pd.read_csv("ytest_original.txt")

<IPython.core.display.Javascript object>

In [7]:
pd_ypredproba_all_class2

0         1         2         3         4         5         6  \
0    0.700000  0.600000  0.400000  0.600000  0.700000  0.000000  0.800000   
1    0.992959  0.874103  0.412963  0.963460  0.894480  0.005756  0.984181   
2    0.966276  0.808556  0.250595  0.873993  0.945025  0.036350  0.983561   
3    0.900000  0.120000  0.060000  0.580000  0.960000  0.000000  0.800000   
4    0.680000  0.720000  0.080000  0.840000  0.620000  0.060000  0.920000   
..        ...       ...       ...       ...       ...       ...       ...   
98   0.859944  0.815526  0.646555  0.808172  0.719945  0.074826  0.974918   
99   0.825188  0.853936  0.649236  0.816580  0.721966  0.050793  0.973557   
100  0.272891  0.367220  0.591495  0.487312  0.431940  0.161098  0.509963   
101  0.317504  0.601828  0.597900  0.524252  0.501321  0.192154  0.468384   
102  0.975537  0.650952  0.169210  0.910468  0.971741  0.050816  0.927759   

            7         8         9  ...       590       591       592  \
0    0.900000  0.700000  0.000000  ...  0.000000  0.000000  0.000000   
1    0.999981  0.919428  0.190981  ...  0.008033  0.116145  0.008953   
2    0.978947  0.956410  0.222362  ...  0.004348  0.134424  0.008143   
3    0.780000  0.960000  0.020000  ...  0.040000  0.020000  0.000000   
4    0.960000  0.780000  0.120000  ...  0.000000  0.020000  0.000000   
..        ...       ...       ...  ...       ...       ...       ...   
98   0.971697  0.916755  0.491769  ...  0.019193  0.374320  0.025014   
99   0.965487  0.912276  0.359732  ...  0.024157  0.399998  0.009150   
100  0.433531  0.453991  0.143212  ...  0.393608  0.442770  0.043037   
101  0.314368  0.503086  0.124005  ...  0.330838  0.369249  0.053748   
102  0.923694  0.871516  0.202806  ...  0.036486  0.084485  0.080224   

          593       594       595       596       597       598       599  
0    0.000000  0.000000  0.000000  0.100000  0.000000  0.000000  0.100000  
1    0.005724  0.019587  0.000006  0.086366  0.004611  0.023565  0.035616  
2    0.002297  0.017564  0.001495  0.077032  0.001742  0.015208  0.014884  
3    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
4    0.000000  0.000000  0.000000  0.020000  0.000000  0.000000  0.000000  
..        ...       ...       ...       ...       ...       ...       ...  
98   0.007776  0.013802  0.019193  0.254435  0.007252  0.008344  0.077484  
99   0.007357  0.032273  0.007385  0.227066  0.007357  0.012236  0.084050  
100  0.043069  0.040613  0.031311  0.238904  0.037711  0.087290  0.416681  
101  0.042346  0.041417  0.029570  0.307241  0.035201  0.087763  0.412489  
102  0.019120  0.022813  0.043722  0.089467  0.008259  0.049439  0.048733  

[103 rows x 600 columns]

<IPython.core.display.Javascript object>

In [8]:
# cross check the values are correct
finalval = np.zeros((600, 2))
temp_pd_ypredproba = pd_ypredproba_all_class2

for i in range(pd_acc_class2.shape[0]):

    predprob = np.column_stack(
        (temp_pd_ypredproba.iloc[i, :], 1 - temp_pd_ypredproba.iloc[i, :])
    )
    finalval += predprob

    print(
        m.f1_score(ytest_class2, np.argmax(predprob, axis=1), average="weighted"),
        pd_acc_class2.iloc[i, 0],
    )

0.8886190707463169 0.8886190707463169
0.9178477001592273 0.9178477001592272
0.9114979197447021 0.911497919744702
0.8381496771461839 0.8381496771461839
0.8867589442471787 0.8867589442471787
0.8738805054594528 0.8738805054594528
0.8943858956735599 0.8943858956735599
0.8722700949024386 0.8722700949024386
0.8653230433253751 0.8653230433253751
0.8627520970908442 0.8627520970908442
0.8452639770518461 0.8452639770518461
0.5586426359575896 0.5586426359575896
0.8504139628552249 0.8504139628552249
0.8725485210611068 0.8725485210611068
0.8643553587249411 0.8643553587249411
0.8405141302537339 0.8405141302537339
0.8440582606925398 0.8440582606925398
0.8605067149800133 0.8605067149800133
0.858573845380832 0.8585738453808319
0.8998792977971848 0.8998792977971848
0.895798319327731 0.895798319327731
0.8846787824990588 0.8846787824990588
0.8943858956735599 0.8943858956735599
0.8630497268160019 0.8630497268160019
0.8493572704099019 0.8493572704099019
0.5991385920405203 0.5991385920405203
0.89438589567355

<IPython.core.display.Javascript object>

In [9]:
# using the accuracy value as a weight value for ensemble
finalval = np.zeros((600, 2))

for i in range(pd_acc_class1.shape[0]):

    predprob = np.column_stack(
        (pd_ypredproba_all_class1.iloc[i, :], 1 - pd_ypredproba_all_class1.iloc[i, :])
    )

    finalval += pd_acc_class0.iloc[i, 0] * predprob

print(
    "f1_score",
    m.f1_score(ytest_class1, np.argmax(finalval, axis=1), average="weighted"),
)
print("accuracy_score", m.accuracy_score(ytest_class1, np.argmax(finalval, axis=1)))

f1_score 0.7180708955384928
accuracy_score 0.7233333333333334


<IPython.core.display.Javascript object>

In [10]:
finalval = np.zeros((600, 2))

temp_pd_ypredproba = pd_ypredproba_all_class0
temp_pd_ypredconfprob = pd_ypredconfprob_all_class0

for i in range(pd_acc_class1.shape[0]):

    predprob = np.column_stack(
        (
            (temp_pd_ypredproba.iloc[i, :] * temp_pd_ypredconfprob.iloc[i, 0])
            + ((1 - temp_pd_ypredproba.iloc[i, :]) * temp_pd_ypredconfprob.iloc[i, 1]),
            ((1 - temp_pd_ypredproba.iloc[i, :]) * temp_pd_ypredconfprob.iloc[i, 3])
            + (temp_pd_ypredproba.iloc[i, :] * temp_pd_ypredconfprob.iloc[i, 2]),
        )
    )

    finalval += predprob

print(
    "f1_score",
    m.f1_score(ytest_class0, np.argmax(finalval, axis=1), average="weighted"),
)
print("accuracy_score", m.accuracy_score(ytest_class0, np.argmax(finalval, axis=1)))

finalval_class0 = finalval.copy() / pd_acc_class0.shape[0]
confmat = m.confusion_matrix(ytest_class0, np.argmax(finalval, axis=1))
confsumh = np.sum(confmat, axis=1)
propconfmat = confmat.copy()
for i in range(propconfmat.shape[0]):
    propconfmat[i] = 100 * propconfmat[i] / confsumh[i]
propconfmat_class0 = propconfmat.ravel() / 100
print(propconfmat_class0)

f1_score 0.8102345415778252
accuracy_score 0.81
[0.72 0.28 0.14 0.85]


<IPython.core.display.Javascript object>

In [11]:
finalval = np.zeros((600, 2))

temp_pd_ypredproba = pd_ypredproba_all_class1
temp_pd_ypredconfprob = pd_ypredconfprob_all_class1

for i in range(pd_acc_class1.shape[0]):

    predprob = np.column_stack(
        (
            (temp_pd_ypredproba.iloc[i, :] * temp_pd_ypredconfprob.iloc[i, 0])
            + ((1 - temp_pd_ypredproba.iloc[i, :]) * temp_pd_ypredconfprob.iloc[i, 1]),
            ((1 - temp_pd_ypredproba.iloc[i, :]) * temp_pd_ypredconfprob.iloc[i, 3])
            + (temp_pd_ypredproba.iloc[i, :] * temp_pd_ypredconfprob.iloc[i, 2]),
        )
    )

    finalval += predprob

print(
    "f1_score",
    m.f1_score(ytest_class1, np.argmax(finalval, axis=1), average="weighted"),
)
print("accuracy_score", m.accuracy_score(ytest_class1, np.argmax(finalval, axis=1)))

finalval_class1 = finalval.copy() / pd_acc_class1.shape[0]
confmat = m.confusion_matrix(ytest_class0, np.argmax(finalval, axis=1))
confsumh = np.sum(confmat, axis=1)
propconfmat = confmat.copy()
for i in range(propconfmat.shape[0]):
    propconfmat[i] = 100 * propconfmat[i] / confsumh[i]
propconfmat_class1 = propconfmat.ravel() / 100
print(propconfmat_class1)

f1_score 0.7364082342511968
accuracy_score 0.7383333333333333
[0.22 0.78 0.36 0.63]


<IPython.core.display.Javascript object>

In [12]:
finalval = np.zeros((600, 2))

temp_pd_ypredproba = pd_ypredproba_all_class2
temp_pd_ypredconfprob = pd_ypredconfprob_all_class2

for i in range(pd_acc_class1.shape[0]):

    predprob = np.column_stack(
        (
            (temp_pd_ypredproba.iloc[i, :] * temp_pd_ypredconfprob.iloc[i, 0])
            + ((1 - temp_pd_ypredproba.iloc[i, :]) * temp_pd_ypredconfprob.iloc[i, 1]),
            ((1 - temp_pd_ypredproba.iloc[i, :]) * temp_pd_ypredconfprob.iloc[i, 3])
            + (temp_pd_ypredproba.iloc[i, :] * temp_pd_ypredconfprob.iloc[i, 2]),
        )
    )

    finalval += predprob

print(
    "f1_score",
    m.f1_score(ytest_class2, np.argmax(finalval, axis=1), average="weighted"),
)
print("accuracy_score", m.accuracy_score(ytest_class2, np.argmax(finalval, axis=1)))

finalval_class2 = finalval.copy() / pd_acc_class2.shape[0]
confmat = m.confusion_matrix(ytest_class2, np.argmax(finalval, axis=1))
confsumh = np.sum(confmat, axis=1)
propconfmat = confmat.copy()
for i in range(propconfmat.shape[0]):
    propconfmat[i] = 100 * propconfmat[i] / confsumh[i]
propconfmat_class2 = propconfmat.ravel() / 100
print(propconfmat_class2)

f1_score 0.918478331240046
accuracy_score 0.92
[0.81 0.18 0.02 0.97]


<IPython.core.display.Javascript object>

In [13]:
acc = [0.8122369749204131, 0.7463460277279999, 0.9223705713932164]

<IPython.core.display.Javascript object>

In [14]:
probablity_not_class0 = (finalval_class0[:, 1] * propconfmat_class0[3]) + (
    finalval_class0[i, 0] * propconfmat_class0[2]
)

probablity_not_class1 = (finalval_class1[:, 1] * propconfmat_class1[3]) + (
    finalval_class1[i, 0] * propconfmat_class1[2]
)
probablity_not_class2 = (finalval_class2[:, 1] * propconfmat_class2[3]) + (
    finalval_class2[i, 0] * propconfmat_class2[2]
)

<IPython.core.display.Javascript object>

In [15]:
probablity_being_class0 = (finalval_class0[:, 0] * propconfmat_class0[0]) + (
    finalval_class0[i, 1] * propconfmat_class0[1]
)

probablity_being_class1 = (finalval_class1[:, 0] * propconfmat_class1[0]) + (
    finalval_class1[i, 1] * propconfmat_class1[1]
)
probablity_being_class2 = (finalval_class2[:, 0] * propconfmat_class2[3]) + (
    finalval_class2[i, 0] * propconfmat_class2[2]
)

<IPython.core.display.Javascript object>

In [16]:
import calculateWeightUsingGa2 as aresult

weightvalga = aresult.getbestvalues(np.array(acc))

0
1
2
3
4
5
6
7
8
9
2.385513997934465 [0.96405632 0.93481231 0.98301626]


<IPython.core.display.Javascript object>

In [17]:
m0 = np.mean(abs(0.5 - finalval_class0[:, 0]))
m1 = np.mean(abs(0.5 - finalval_class1[:, 0]))
m2 = np.mean(abs(0.5 - finalval_class2[:, 0]))
ms = m0 + m1 + m2

w0 = m0 / ms
w1 = m1 / ms
w2 = m2 / ms

<IPython.core.display.Javascript object>

In [18]:
pc0 = probablity_being_class0 * probablity_not_class1 * probablity_not_class2
pc1 = probablity_being_class1 * probablity_not_class0 * probablity_not_class2
pc2 = probablity_being_class2 * probablity_not_class0 * probablity_not_class1

<IPython.core.display.Javascript object>

In [19]:
finalcol = np.zeros((ytest_original.shape[0], 3))
finalcol[:, 0] = pc0 * weightvalga[0]
finalcol[:, 1] = pc1 * weightvalga[1]
finalcol[:, 2] = pc2 * weightvalga[2]
finalpred = np.argmax(finalcol, axis=1)

ytest = ytest_original.copy()
print(m.accuracy_score(ytest, finalpred))
print(m.confusion_matrix(ytest, finalpred))
temppred = finalpred

0.7266666666666667
[[161  39   0]
 [ 75 115  10]
 [  4  36 160]]


<IPython.core.display.Javascript object>