In [1]:
%load_ext nb_black

In [2]:
import numpy as np
import pandas as pd
from sklearn import metrics as m

<IPython.core.display.Javascript object>

In [3]:
pd_acc_class0 = pd.read_csv("pd_acc_class0.txt")
pd_ypredproba_all_class0 = pd.read_csv("pd_ypredproba_all_class0.txt")
pd_ypredconfprob_all_class0 = pd.read_csv("pd_ypredconfprob_all_class0.txt")

<IPython.core.display.Javascript object>

In [4]:
pd_acc_class1 = pd.read_csv("pd_acc_class1.txt")
pd_ypredproba_all_class1 = pd.read_csv("pd_ypredproba_all_class1.txt")
pd_ypredconfprob_all_class1 = pd.read_csv("pd_ypredconfprob_all_class1.txt")

<IPython.core.display.Javascript object>

In [5]:
pd_acc_class2 = pd.read_csv("pd_acc_class2.txt")
pd_ypredproba_all_class2 = pd.read_csv("pd_ypredproba_all_class2.txt")
pd_ypredconfprob_all_class2 = pd.read_csv("pd_ypredconfprob_all_class2.txt")

<IPython.core.display.Javascript object>

In [6]:
ytest_class0 = pd.read_csv("ytest_class0.txt")
ytest_class1 = pd.read_csv("ytest_class1.txt")
ytest_class2 = pd.read_csv("ytest_class2.txt")
ytest_original = pd.read_csv("ytest_original.txt")

<IPython.core.display.Javascript object>

In [7]:
pd_ypredproba_all_class0.head()

0         1         2         3         4         5         6  \
0  0.000000  0.000000  0.100000  0.000000  0.000000  0.600000  0.000000   
1  0.053085  0.035696  0.101903  0.042193  0.228468  0.396880  0.160072   
2  0.001439  0.002363  0.058239  0.005408  0.002295  0.681239  0.000936   
3  0.000000  0.060000  0.240000  0.000000  0.020000  0.340000  0.100000   
4  0.004383  0.008302  0.072385  0.010435  0.007669  0.692125  0.004383   

          7         8         9  ...       590       591       592       593  \
0  0.000000  0.000000  0.300000  ...  0.500000  0.200000  1.000000  0.800000   
1  0.004607  0.065926  0.187085  ...  0.256247  0.161606  0.733219  0.802460   
2  0.003650  0.002405  0.100384  ...  0.604715  0.109936  0.803831  0.869039   
3  0.060000  0.000000  0.200000  ...  0.620000  0.280000  0.660000  0.500000   
4  0.008084  0.005516  0.109870  ...  0.616562  0.136697  0.800308  0.858310   

        594       595       596       597       598       599  
0  0.800000  0.800000  0.200000  1.000000  0.700000  0.300000  
1  0.481447  0.850987  0.445272  0.808809  0.741343  0.294490  
2  0.684544  0.908467  0.236095  0.878567  0.813042  0.438247  
3  0.560000  0.780000  0.400000  0.820000  0.570000  0.400000  
4  0.652514  0.884555  0.248048  0.868501  0.784045  0.426801  

[5 rows x 600 columns]

<IPython.core.display.Javascript object>

In [8]:
# cross check the values are correct
finalval = np.zeros((600, 2))
temp_pd_ypredproba = pd_ypredproba_all_class1

for i in range(pd_acc_class0.shape[0]):

    predprob = np.column_stack(
        (temp_pd_ypredproba.iloc[i, :], 1 - temp_pd_ypredproba.iloc[i, :])
    )
    finalval += predprob

    print(
        m.f1_score(ytest_class1, np.argmax(predprob, axis=1), average="weighted"),
        pd_acc_class1.iloc[i, 0],
    )

0.6765880295918836 0.6765880295918836
0.5333333333333333 0.5333333333333333
0.7315606204495092 0.7315606204495092
0.707403055229142 0.7074030552291422
0.738221824835998 0.738221824835998
0.6638991645950051 0.6638991645950051
0.738221824835998 0.738221824835998
0.7222786009065693 0.7222786009065693
0.738221824835998 0.738221824835998
0.531970551784451 0.531970551784451
0.738221824835998 0.738221824835998
0.6824826901424683 0.6824826901424683
0.738221824835998 0.738221824835998
0.681905864197531 0.6819058641975311
0.738221824835998 0.738221824835998
0.5593806873476636 0.5593806873476636
0.738221824835998 0.738221824835998
0.5526837353237751 0.5526837353237751
0.738221824835998 0.738221824835998
0.6829492030730421 0.6829492030730421
0.738221824835998 0.738221824835998
0.7142049176335639 0.7142049176335639
0.738221824835998 0.738221824835998
0.6907048064469141 0.6907048064469141
0.738221824835998 0.738221824835998
0.6712963101541852 0.6712963101541852
0.738221824835998 0.738221824835998
0.

<IPython.core.display.Javascript object>

In [9]:
# using the accuracy value as a weight value for ensemble
finalval = np.zeros((600, 2))

for i in range(pd_acc_class1.shape[0]):

    predprob = np.column_stack(
        (pd_ypredproba_all_class1.iloc[i, :], 1 - pd_ypredproba_all_class1.iloc[i, :])
    )

    finalval += pd_acc_class0.iloc[i, 0] * predprob

print(
    "f1_score",
    m.f1_score(ytest_class1, np.argmax(finalval, axis=1), average="weighted"),
)
print("accuracy_score", m.accuracy_score(ytest_class1, np.argmax(finalval, axis=1)))

f1_score 0.7415041974474262
accuracy_score 0.7416666666666667


<IPython.core.display.Javascript object>

In [10]:
finalval = np.zeros((600, 2))

temp_pd_ypredproba = pd_ypredproba_all_class0
temp_pd_ypredconfprob = pd_ypredconfprob_all_class0

for i in range(pd_acc_class1.shape[0]):

    predprob = np.column_stack(
        (
            (temp_pd_ypredproba.iloc[i, :] * temp_pd_ypredconfprob.iloc[i, 0])
            + ((1 - temp_pd_ypredproba.iloc[i, :]) * temp_pd_ypredconfprob.iloc[i, 1]),
            ((1 - temp_pd_ypredproba.iloc[i, :]) * temp_pd_ypredconfprob.iloc[i, 3])
            + (temp_pd_ypredproba.iloc[i, :] * temp_pd_ypredconfprob.iloc[i, 2]),
        )
    )

    finalval += predprob

print(
    "f1_score",
    m.f1_score(ytest_class0, np.argmax(finalval, axis=1), average="weighted"),
)
print("accuracy_score", m.accuracy_score(ytest_class0, np.argmax(finalval, axis=1)))

finalval_class0 = finalval.copy() / pd_acc_class0.shape[0]
confmat = m.confusion_matrix(ytest_class0, np.argmax(finalval, axis=1))
confsumh = np.sum(confmat, axis=1)
propconfmat = confmat.copy()
for i in range(propconfmat.shape[0]):
    propconfmat[i] = 100 * propconfmat[i] / confsumh[i]
propconfmat_class0 = propconfmat.ravel() / 100
print(propconfmat_class0)

f1_score 0.8122369749204131
accuracy_score 0.8116666666666666
[0.73 0.27 0.14 0.85]


<IPython.core.display.Javascript object>

In [11]:
finalval = np.zeros((600, 2))

temp_pd_ypredproba = pd_ypredproba_all_class1
temp_pd_ypredconfprob = pd_ypredconfprob_all_class1

for i in range(pd_acc_class1.shape[0]):

    predprob = np.column_stack(
        (
            (temp_pd_ypredproba.iloc[i, :] * temp_pd_ypredconfprob.iloc[i, 0])
            + ((1 - temp_pd_ypredproba.iloc[i, :]) * temp_pd_ypredconfprob.iloc[i, 1]),
            ((1 - temp_pd_ypredproba.iloc[i, :]) * temp_pd_ypredconfprob.iloc[i, 3])
            + (temp_pd_ypredproba.iloc[i, :] * temp_pd_ypredconfprob.iloc[i, 2]),
        )
    )

    finalval += predprob

print(
    "f1_score",
    m.f1_score(ytest_class1, np.argmax(finalval, axis=1), average="weighted"),
)
print("accuracy_score", m.accuracy_score(ytest_class1, np.argmax(finalval, axis=1)))

finalval_class1 = finalval.copy() / pd_acc_class1.shape[0]
confmat = m.confusion_matrix(ytest_class0, np.argmax(finalval, axis=1))
confsumh = np.sum(confmat, axis=1)
propconfmat = confmat.copy()
for i in range(propconfmat.shape[0]):
    propconfmat[i] = 100 * propconfmat[i] / confsumh[i]
propconfmat_class1 = propconfmat.ravel() / 100
print(propconfmat_class1)

f1_score 0.7463460277279999
accuracy_score 0.7466666666666667
[0.22 0.77 0.38 0.61]


<IPython.core.display.Javascript object>

In [12]:
finalval = np.zeros((600, 2))

temp_pd_ypredproba = pd_ypredproba_all_class2
temp_pd_ypredconfprob = pd_ypredconfprob_all_class2

for i in range(pd_acc_class1.shape[0]):

    predprob = np.column_stack(
        (
            (temp_pd_ypredproba.iloc[i, :] * temp_pd_ypredconfprob.iloc[i, 0])
            + ((1 - temp_pd_ypredproba.iloc[i, :]) * temp_pd_ypredconfprob.iloc[i, 1]),
            ((1 - temp_pd_ypredproba.iloc[i, :]) * temp_pd_ypredconfprob.iloc[i, 3])
            + (temp_pd_ypredproba.iloc[i, :] * temp_pd_ypredconfprob.iloc[i, 2]),
        )
    )

    finalval += predprob

print(
    "f1_score",
    m.f1_score(ytest_class2, np.argmax(finalval, axis=1), average="weighted"),
)
print("accuracy_score", m.accuracy_score(ytest_class2, np.argmax(finalval, axis=1)))

finalval_class2 = finalval.copy() / pd_acc_class2.shape[0]
confmat = m.confusion_matrix(ytest_class2, np.argmax(finalval, axis=1))
confsumh = np.sum(confmat, axis=1)
propconfmat = confmat.copy()
for i in range(propconfmat.shape[0]):
    propconfmat[i] = 100 * propconfmat[i] / confsumh[i]
propconfmat_class2 = propconfmat.ravel() / 100
print(propconfmat_class2)

f1_score 0.9223705713932164
accuracy_score 0.9233333333333333
[0.84 0.16 0.03 0.96]


<IPython.core.display.Javascript object>

In [13]:
acc = [0.8122369749204131, 0.7463460277279999, 0.9223705713932164]

<IPython.core.display.Javascript object>

In [14]:
probablity_not_class0 = (finalval_class0[:, 1] * propconfmat_class0[3]) + (
    finalval_class0[i, 0] * propconfmat_class0[2]
)

probablity_not_class1 = (finalval_class1[:, 1] * propconfmat_class1[3]) + (
    finalval_class1[i, 0] * propconfmat_class1[2]
)
probablity_not_class2 = (finalval_class2[:, 1] * propconfmat_class2[3]) + (
    finalval_class2[i, 0] * propconfmat_class2[2]
)

<IPython.core.display.Javascript object>

In [15]:
probablity_being_class0 = (finalval_class0[:, 0] * propconfmat_class0[0]) + (
    finalval_class0[i, 1] * propconfmat_class0[1]
)

probablity_being_class1 = (finalval_class1[:, 0] * propconfmat_class1[0]) + (
    finalval_class1[i, 1] * propconfmat_class1[1]
)
probablity_being_class2 = (finalval_class2[:, 0] * propconfmat_class2[3]) + (
    finalval_class2[i, 0] * propconfmat_class2[2]
)

<IPython.core.display.Javascript object>

In [16]:
import calculateWeightUsingGa2 as aresult

weightvalga = aresult.getbestvalues(np.array(acc))

0
1
2
3
4
5
6
7
8
9
2.428668852916947 [0.98032178 0.96069899 0.99384604]


<IPython.core.display.Javascript object>

In [17]:
m0 = np.mean(abs(0.5 - finalval_class0[:, 0]))
m1 = np.mean(abs(0.5 - finalval_class1[:, 0]))
m2 = np.mean(abs(0.5 - finalval_class2[:, 0]))
ms = m0 + m1 + m2

w0 = m0 / ms
w1 = m1 / ms
w2 = m2 / ms

<IPython.core.display.Javascript object>

In [18]:
pc0 = probablity_being_class0 * probablity_not_class1 * probablity_not_class2
pc1 = probablity_being_class1 * probablity_not_class0 * probablity_not_class2
pc2 = probablity_being_class2 * probablity_not_class0 * probablity_not_class1

<IPython.core.display.Javascript object>

In [19]:
finalcol = np.zeros((ytest_original.shape[0], 3))
finalcol[:, 0] = weightvalga[0] * pc0
finalcol[:, 1] = weightvalga[1] * pc1
finalcol[:, 2] = weightvalga[2] * pc2
finalpred = np.argmax(finalcol, axis=1)

ytest = ytest_original.copy()
print(m.accuracy_score(ytest, finalpred))
print(m.confusion_matrix(ytest, finalpred))
temppred = finalpred

0.7333333333333333
[[151  49   0]
 [ 63 124  13]
 [  4  31 165]]


<IPython.core.display.Javascript object>